name: Build

on: push

jobs:

  windows:
    runs-on: windows-latest
    name: Windows
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          fftw:p

    # Disable glibc specific checks and headers
    - name: Patch & build liquid-dsp
      shell: msys2 {0}
      run: |
        git clone https://github.com/jgaeddert/liquid-dsp.git && cd liquid-dsp
        perl -i -p -e 's/(AC_CHECK_LIB\(\[c\].+| sys\/resource.h)//g' configure.ac
        ./bootstrap.sh && ./configure --prefix=/mingw64 && make
        make install
        
